### ISSUE TITLE
rootlyhq/pulse-action@main does not respect the `source` argument

### ISSUE THREAD

**Issue by BrianHicks** [rootlyhq/pulse-action#3]
Given this configuration:

```yaml
      - name: rootly-pulse
        uses: rootlyhq/pulse-action@main
        with:
          api_key: ${{ secrets.ROOTLY_API_KEY }}
          summary: Lighthouse evaluated the latest deploy
          environments: production
          labels: status=${{ needs.lighthouse.result }}
          source: Lighthouse
          refs: sha=${{ github.sha }}
```

The logs show:

```
Created a pulse with the following values: 

  Summary:      Lighthouse evaluated the latest deploy
  Started At:   08 Feb 24 16:22 UTC
  Ended At      08 Feb 24 16:22 UTC
  Services:     None
  Environments: production
  Labels:       
    status = failure

  Source:       cli
  Refs:         
    sha = d2e958949f
```

Notice that the "Source" is different in the logs than it is in the configuration.

This has caused a bunch of false-alarm fires in my org this morning; I'd appreciate a fix!
